// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/lifegame.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LifeService_StreamEvolution_FullMethodName = "/golife.LifeService/StreamEvolution"
)

// LifeServiceClient is the client API for LifeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LifeServiceClient interface {
	StreamEvolution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimulationRequest, SimulationUpdate], error)
}

type lifeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLifeServiceClient(cc grpc.ClientConnInterface) LifeServiceClient {
	return &lifeServiceClient{cc}
}

func (c *lifeServiceClient) StreamEvolution(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SimulationRequest, SimulationUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LifeService_ServiceDesc.Streams[0], LifeService_StreamEvolution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SimulationRequest, SimulationUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LifeService_StreamEvolutionClient = grpc.BidiStreamingClient[SimulationRequest, SimulationUpdate]

// LifeServiceServer is the server API for LifeService service.
// All implementations must embed UnimplementedLifeServiceServer
// for forward compatibility.
type LifeServiceServer interface {
	StreamEvolution(grpc.BidiStreamingServer[SimulationRequest, SimulationUpdate]) error
	mustEmbedUnimplementedLifeServiceServer()
}

// UnimplementedLifeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLifeServiceServer struct{}

func (UnimplementedLifeServiceServer) StreamEvolution(grpc.BidiStreamingServer[SimulationRequest, SimulationUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamEvolution not implemented")
}
func (UnimplementedLifeServiceServer) mustEmbedUnimplementedLifeServiceServer() {}
func (UnimplementedLifeServiceServer) testEmbeddedByValue()                     {}

// UnsafeLifeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LifeServiceServer will
// result in compilation errors.
type UnsafeLifeServiceServer interface {
	mustEmbedUnimplementedLifeServiceServer()
}

func RegisterLifeServiceServer(s grpc.ServiceRegistrar, srv LifeServiceServer) {
	// If the following call panics, it indicates UnimplementedLifeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LifeService_ServiceDesc, srv)
}

func _LifeService_StreamEvolution_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LifeServiceServer).StreamEvolution(&grpc.GenericServerStream[SimulationRequest, SimulationUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LifeService_StreamEvolutionServer = grpc.BidiStreamingServer[SimulationRequest, SimulationUpdate]

// LifeService_ServiceDesc is the grpc.ServiceDesc for LifeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LifeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "golife.LifeService",
	HandlerType: (*LifeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvolution",
			Handler:       _LifeService_StreamEvolution_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/lifegame.proto",
}
