// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/lifegame.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Board struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Width  int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	// Types that are valid to be assigned to DataFormat:
	//
	//	*Board_RleString
	//	*Board_RawCells
	DataFormat    isBoard_DataFormat `protobuf_oneof:"data_format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_api_lifegame_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_api_lifegame_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_api_lifegame_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Board) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Board) GetDataFormat() isBoard_DataFormat {
	if x != nil {
		return x.DataFormat
	}
	return nil
}

func (x *Board) GetRleString() string {
	if x != nil {
		if x, ok := x.DataFormat.(*Board_RleString); ok {
			return x.RleString
		}
	}
	return ""
}

func (x *Board) GetRawCells() []byte {
	if x != nil {
		if x, ok := x.DataFormat.(*Board_RawCells); ok {
			return x.RawCells
		}
	}
	return nil
}

type isBoard_DataFormat interface {
	isBoard_DataFormat()
}

type Board_RleString struct {
	RleString string `protobuf:"bytes,3,opt,name=rle_string,json=rleString,proto3,oneof"`
}

type Board_RawCells struct {
	RawCells []byte `protobuf:"bytes,4,opt,name=raw_cells,json=rawCells,proto3,oneof"`
}

func (*Board_RleString) isBoard_DataFormat() {}

func (*Board_RawCells) isBoard_DataFormat() {}

type SimulationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialState  *Board                 `protobuf:"bytes,1,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"` // Скорость симуляции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationRequest) Reset() {
	*x = SimulationRequest{}
	mi := &file_api_lifegame_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationRequest) ProtoMessage() {}

func (x *SimulationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_lifegame_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationRequest.ProtoReflect.Descriptor instead.
func (*SimulationRequest) Descriptor() ([]byte, []int) {
	return file_api_lifegame_proto_rawDescGZIP(), []int{1}
}

func (x *SimulationRequest) GetInitialState() *Board {
	if x != nil {
		return x.InitialState
	}
	return nil
}

func (x *SimulationRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type SimulationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentState  *Board                 `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Generation    int32                  `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationUpdate) Reset() {
	*x = SimulationUpdate{}
	mi := &file_api_lifegame_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationUpdate) ProtoMessage() {}

func (x *SimulationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_lifegame_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationUpdate.ProtoReflect.Descriptor instead.
func (*SimulationUpdate) Descriptor() ([]byte, []int) {
	return file_api_lifegame_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationUpdate) GetCurrentState() *Board {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *SimulationUpdate) GetGeneration() int32 {
	if x != nil {
		return x.Generation
	}
	return 0
}

var File_api_lifegame_proto protoreflect.FileDescriptor

const file_api_lifegame_proto_rawDesc = "" +
	"\n" +
	"\x12api/lifegame.proto\x12\x03api\"\x84\x01\n" +
	"\x05Board\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x1f\n" +
	"\n" +
	"rle_string\x18\x03 \x01(\tH\x00R\trleString\x12\x1d\n" +
	"\traw_cells\x18\x04 \x01(\fH\x00R\brawCellsB\r\n" +
	"\vdata_format\"_\n" +
	"\x11SimulationRequest\x12/\n" +
	"\rinitial_state\x18\x01 \x01(\v2\n" +
	".api.BoardR\finitialState\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"c\n" +
	"\x10SimulationUpdate\x12/\n" +
	"\rcurrent_state\x18\x01 \x01(\v2\n" +
	".api.BoardR\fcurrentState\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x05R\n" +
	"generation2S\n" +
	"\vLifeService\x12D\n" +
	"\x0fStreamEvolution\x12\x16.api.SimulationRequest\x1a\x15.api.SimulationUpdate(\x010\x01B!Z\x1f://github.com/rsvato/golife;apib\x06proto3"

var (
	file_api_lifegame_proto_rawDescOnce sync.Once
	file_api_lifegame_proto_rawDescData []byte
)

func file_api_lifegame_proto_rawDescGZIP() []byte {
	file_api_lifegame_proto_rawDescOnce.Do(func() {
		file_api_lifegame_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_lifegame_proto_rawDesc), len(file_api_lifegame_proto_rawDesc)))
	})
	return file_api_lifegame_proto_rawDescData
}

var file_api_lifegame_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_lifegame_proto_goTypes = []any{
	(*Board)(nil),             // 0: api.Board
	(*SimulationRequest)(nil), // 1: api.SimulationRequest
	(*SimulationUpdate)(nil),  // 2: api.SimulationUpdate
}
var file_api_lifegame_proto_depIdxs = []int32{
	0, // 0: api.SimulationRequest.initial_state:type_name -> api.Board
	0, // 1: api.SimulationUpdate.current_state:type_name -> api.Board
	1, // 2: api.LifeService.StreamEvolution:input_type -> api.SimulationRequest
	2, // 3: api.LifeService.StreamEvolution:output_type -> api.SimulationUpdate
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_lifegame_proto_init() }
func file_api_lifegame_proto_init() {
	if File_api_lifegame_proto != nil {
		return
	}
	file_api_lifegame_proto_msgTypes[0].OneofWrappers = []any{
		(*Board_RleString)(nil),
		(*Board_RawCells)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_lifegame_proto_rawDesc), len(file_api_lifegame_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_lifegame_proto_goTypes,
		DependencyIndexes: file_api_lifegame_proto_depIdxs,
		MessageInfos:      file_api_lifegame_proto_msgTypes,
	}.Build()
	File_api_lifegame_proto = out.File
	file_api_lifegame_proto_goTypes = nil
	file_api_lifegame_proto_depIdxs = nil
}
